### ISSUE TITLE
Offset between planned and executed experiments

### ISSUE THREAD

**Issue by JB-Wolf** [cambiegroup/flowchem#9]
# Problem
Granularity of settable flow rates is limited. For that reason, theoretically continuous parameters become quantized. With this a rounding error is introduced, introducing an offset between planned and actually executed experiment.

# Solution
Feed executed parameters back and thereby update the theoretically planned experiment to the practically implemented experiment by calculation backwards.

**Comment by dcambie** [comment]
I'd say as far as we don't use the ML600 for streams that have to be accurate this is no more an issue?
